### ISSUE TITLE
支持 template.yml 内函数属性自动补全

### ISSUE THREAD

**Issue by vangie** [alibaba/serverless-vscode#21]
如下 template.yml

```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  my-test:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 'helloworld'
    my-test:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs8
        CodeUri: './'
```

在 CodeUri 后一行输入 Env 不会出现 EnvironmentVariables 补全提示。
