### ISSUE TITLE
关于template.yml 提示 CronExpression 的问题

### ISSUE THREAD

**Issue by LiHaoGit** [alibaba/serverless-vscode#226]
**Describe the bug**
当 Events 有多个 TmTrigger 的时候，鼠标悬浮在 CronExpression 字段的值，只有最后一个才显示提示信息，前几个不显示

**Expected behavior**
鼠标悬浮在每一个 CronExpression  上 ，都应该显示提示信息

**Screenshots**
鼠标悬浮在在第一个与第二个 CronExpression  上  
![image](https://user-images.githubusercontent.com/7036191/79969050-8ac6e080-84c3-11ea-9713-b9baa84c845e.png)

鼠标悬浮在最后一个 CronExpression  上  
![image](https://user-images.githubusercontent.com/7036191/79969100-9a462980-84c3-11ea-9e6e-27380f8cc4d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode Version: 1.44.2
 - Aliyun Serverless Extension Version 1.27.7

```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  stream01:
    Type: 'Aliyun::Serverless::Service'      
    Properties:
    processdata:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs10
        Description: 处理日、周、月、年数据
        CodeUri: ./processdata
        MemorySize: 128
        Timeout: 120  
      Events: 
        TmTrigger:
          Type: Timer
          Properties:             
            CronExpression: "0 30 0 1 * *"  # 月
            Enable: true 
        TmTrigger:
          Type: Timer
          Properties:             
            CronExpression: "0 30 15 * * 7"  # 周
            Enable: true  
        TmTrigger:
          Type: Timer
          Properties:             
            CronExpression: "0 20 15 * * *"  # 天
            Enable: true 
```
