### ISSUE TITLE
在 fun.yml 文件里也会触发 template.yml 的自动补全

### ISSUE THREAD

**Issue by vangie** [alibaba/serverless-vscode#23]
应该只在 template.yml 文件里触发，不影响其他 yml 文件。

```
runtime: nodejs8
tasks:
  - apt: ndiff
    local: tablestore: # tablestore name
      Type: 'Aliyun::Serverless::TableStore'
      Properties:
        ClusterType: HYBRID
      table: # table name
        Type: 'Aliyun::Serverless::TableStore::Table'
        Properties:
          PrimaryKeyList:
            - Name: uid
              Type: STRING
  - apt: nmap

```
