### ISSUE TITLE
部署代码报400错误

### ISSUE THREAD

**Issue by yalishizhude** [alibaba/serverless-vscode#236]
**Describe the bug**
部署本地代码时，控制台报400错误

**To Reproduce**
1. 点击部署按钮。

**Expected behavior**
上传成功

**Screenshots**
![image](https://user-images.githubusercontent.com/3870098/82634472-57957f80-9c30-11ea-96bd-415b8b228eab.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows8, MacOS 10.14.5]
 - VSCode-insider: 1.46.0
 - Aliyun Serverless Extension Version ：1.27.11

配置信息

```
ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  gtx-order:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      InternetAccess: true
    index:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: python3
        Timeout: 10
        MemorySize: 512
        InstanceConcurrency: 1
        EnvironmentVariables: 
          order_db_host_local: host.docker.internal
        CodeUri: ./aliyun-serverless
      Events:
        router:
          Type: HTTP
          Properties:
            AuthType: anonymous
            Methods:
              - GET
              - POST
              - PUT
              - DELETE
```
